projects:
  app:
    schemaPath: schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: ./prisma.graphql
    extensions:
      prisma: database/prisma.yml